version: '3'
services:
  web:
    platform: linux/x86_64
    build: ./
    ports:
      - "3001:3000"
    working_dir: "/src"
    volumes:
      - ./src:/src
      - node_modules_volume:/src/node_modules
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume: